Fix running on GNOME 3.36
pop-os/gnome-shell-extension-always-show-workspaces pull request #7
Opened 2020-04-21 19:10 UTC by crawfxrd

Handle changes made to overview in gnome-shell [`91eb84fa4eada`](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/91eb84fa4eada).

Resolves: #5 
Resolves: #6

2020-04-21 19:22 UTC, jackpot51 submitted a review, later dismissed

2020-04-22 14:43 UTC, brs17 requested changes
This does fix the extension in 20.04. The extension continues to function properly in 18.04, but the extension no longer works properly in 19.10. I see the following logs in journald:

```
Apr 22 08:39:23 pop-os gnome-shell[1598]: JS WARNING: [/usr/share/gnome-shell/extensions/always-show-workspaces@system76.com/extension.js 10]: reference to undefined property "_controls"
Apr 22 08:39:23 pop-os gnome-shell[1598]: JS ERROR: Extension always-show-workspaces@system76.com: TypeError: overview._controls is undefined
                                          enable@/usr/share/gnome-shell/extensions/always-show-workspaces@system76.com/extension.js:10:5
                                          _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:149:13
                                          loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:281:21
                                          _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:499:13
                                          collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
                                          _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:474:9
                                          _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:508:13
                                          _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:539:13
                                          init@resource:///org/gnome/shell/ui/extensionSystem.js:49:9
                                          _initializeUI@resource:///org/gnome/shell/ui/main.js:245:5
                                          start@resource:///org/gnome/shell/ui/main.js:141:5
                                          @<main>:1:31
```

2020-04-22 16:54 UTC, crawfxrd commented
`Main.overview._overview` is a valid object in GNOME 3.34, but not the one we want. I've changed it to get the controls manager instead of the overview actor.

2020-04-22 18:18 UTC, brs17 approved these changes
Looks good now!

2020-04-22 18:47 UTC, jackpot51 approved these changes

2020-04-22 18:48 UTC, merged